CLASSES: Car


MODEL:
    number_block: 3



# general training config
TRAIN:
    SPLIT: train #aug_train
    VAL_SPLIT: smallval

    LR: 0.002
    LR_CLIP: 0.00001
    LR_DECAY: 0.5
    DECAY_STEP_LIST: [100, 150, 180, 200]
    LR_WARMUP: True
    WARMUP_MIN: 0.0002
    WARMUP_EPOCH: 1

    BN_MOMENTUM: 0.1
    BN_DECAY: 0.5
    BNM_CLIP: 0.01
    BN_DECAY_STEP_LIST: [1000]

    OPTIMIZER: adam_onecycle  # adam, adam_onecycle
    WEIGHT_DECAY: 0.001  # L2 regularization
    MOMENTUM: 0.9

    MOMS: [0.95, 0.85]
    DIV_FACTOR: 10.0
    PCT_START: 0.4

    GRAD_NORM_CLIP: 1.0

    RPN_PRE_NMS_TOP_N: 9000
    RPN_POST_NMS_TOP_N: 512
    RPN_NMS_THRESH: 0.85
    RPN_DISTANCE_BASED_PROPOSE: True
    ##
    RPN_TRAIN_WEIGHT: 1.0
    RCNN_TRAIN_WEIGHT: 1.0
    CE_WEIGHT: 5.0
    IOU_LOSS_TYPE: cls_mask_with_bin #raw
    BBOX_AVG_BY_BIN: True
    RY_WITH_BIN: False

TEST:
    SPLIT: val #test #test #val #test #val #test #val
    RPN_PRE_NMS_TOP_N: 9000 #9000
    RPN_POST_NMS_TOP_N: 100 #100
    RPN_NMS_THRESH: 0.8
    RPN_DISTANCE_BASED_PROPOSE: True

    ##
    BBOX_AVG_BY_BIN: True
    RY_WITH_BIN: False
